# Generated by Django 3.2 on 2022-07-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LSN', models.BigIntegerField()),
                ('sdf', models.TextField(max_length=100000)),
            ],
        ),
    ]
